# Generated by Django 2.1.2 on 2019-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='reserve_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
