# Generated by Django 2.1.2 on 2019-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0002_auto_20190610_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='play_style',
            field=models.CharField(choices=[('ENJOY', 'エンジョイ'), ('HARD', 'ガチ'), ('NOTHING', 'とりあえず一緒にプレイ')], default='ENJOY', max_length=20),
        ),
        migrations.AddField(
            model_name='matching',
            name='secret_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matching',
            name='voice_chat',
            field=models.BooleanField(default=False),
        ),
    ]
