# Generated by Django 2.1.2 on 2019-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0003_auto_20190611_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='play_style',
            field=models.CharField(choices=[('エンジョイ', 'エンジョイ'), ('ガチ', 'ガチ'), ('とりあえず一緒にプレイ', 'とりあえず一緒にプレイ')], default='エンジョイ', max_length=20),
        ),
    ]
