# Generated by Django 2.1.2 on 2019-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtournament',
            name='limitParticipant',
            field=models.IntegerField(default=4),
        ),
    ]
