# Generated by Django 2.1.2 on 2019-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_psn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='account_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_enable',
            field=models.BooleanField(default=False),
        ),
    ]
