# Generated by Django 2.1.2 on 2019-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20190625_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/no_image.png', upload_to='account_image'),
        ),
    ]
